apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  ports:
  - port: 8080
    name: "8080"
    targetPort: 8080
  selector:
    service: udagram-reverseproxy
  type: LoadBalancer 
